Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Models/Customer.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace AdminWebPortal.Models;

public class Customer {
    public int CustomerID { get; set; }

    [Required, StringLength(50)]
    public string Name { get; set; }

    [StringLength(11)]
    public string TFN { get; set; }

    [StringLength(50)]
    public string Address { get; set; }

    [StringLength(40)]
    public string Suburb { get; set; }

    [StringLength(3, MinimumLength = 2)]
    public string State { get; set; }

    [StringLength(4, MinimumLength = 4)]
    [RegularExpression("^[0-9]+$")]
    public string Postcode { get; set; }

    //The regular expression should conform to an Australian phone number
    [StringLength(12)]
    [RegularExpression("^(?:\\((?=.*\\)))?(0?[4])\\)? (\\d\\d([ ](?=\\d{3})|(?!\\d\\d[- ]?\\d[- ]))\\d\\d[- ]?\\d[- ]?\\d{3})$")]
    public string Mobile { get; set; }

    public bool Locked { get; set; }

    [JsonProperty("accounts")]
    public List<Account> Accounts { get; set; }
}

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Models/Transaction.cs
using System.ComponentModel.DataAnnotations;

namespace AdminWebPortal.Models;

public enum TransactionType {
    Deposit = 1,
    Withdraw = 2,
    TransferDebit = 3,
    TransferCredit = 4,
    ServiceCharge = 5
}
public class Transaction {
    public int TransactionID { get; set; }

    [Required]
    public TransactionType TransactionType { get; set; }

    [Required]
    public int AccountNumber { get; set; }

    public int? DestinationAccountNumber { get; set; }

    [Required]
    public decimal Amount { get; set; }

    [StringLength(30, ErrorMessage = ("Maximum of 30 characters in a comment"))]
    public string Comment { get; set; }

    [Required]
    public DateTime TransactionTimeUTC { get; set; }
}

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Controllers/AdminPanelController.cs
using Microsoft.AspNetCore.Mvc;
using AdminWebPortal.Models;
using AdminWebPortal.Filters;
using AdminWebPortal.Helpers;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace AdminWebPortal.Controllers;

[AuthorizeAdmin]
public class AdminPanelController : Controller {
    public async Task<IActionResult> Index() {
        HttpContext.Session.Remove("customerID");
        //GET:Customers
        List<Customer> customers = await CustomerFetcher.GetAllCustomersAsync();

        return View(customers);
    }

    [HttpPost]
    public async Task<IActionResult> Search(string customerID) {
        //GET:Customers
        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        if (customer != null) {
            HttpContext.Session.SetString("customerID", customerID);
            return RedirectToAction("Customer", "AdminPanel");
        }

        return RedirectToAction("Index", "AdminPanel");
    }

    public async Task<IActionResult> Customer() {
        string customerID = HttpContext.Session.GetString("customerID");

        //GET:Customers
        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        return View(customer);
    }

    public async Task<IActionResult> Transactions(int id) {
        List<Transaction> transactions = new List<Transaction>();

        using (var client = new HttpClient()) {
            client.BaseAddress = new Uri("https://localhost:7291/api/Accounts/");
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage httpResponseMessage = await client.GetAsync(id + "/Transactions");
            if (httpResponseMessage.IsSuccessStatusCode) {
                var empResponse = httpResponseMessage.Content.ReadAsStringAsync().Result;
                transactions = JsonConvert.DeserializeObject<List<Transaction>>(empResponse);
            }
            else {
                Console.Error.WriteLine(id);    
            }

            return View(transactions);
        }
    }
}

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Controllers/BillPayController.cs
using AdminWebPortal.Helpers;
using AdminWebPortal.Models;
using AdminWebPortal.Filters;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Net.Http.Headers;

namespace AdminWebPortal.Controllers;

[AuthorizeAdmin]
public class BillPayController : Controller {
    public async Task<IActionResult> Index(int id) {
        //GET:BillPays
        List<BillPay> billPays = await BillPayFetcher.GetAllBillsAsync(id.ToString());

        return View(billPays);
    }

    public async Task<IActionResult> Freeze(string id, int accountnumber) {
        BillPay billPay = await BillPayFetcher.GetBillByIDAsync(id);

        billPay.Status = Status.Frozen;

        var content = new StringContent(JsonConvert.SerializeObject(billPay), Encoding.UTF8, "application/json");

        using (var client = new HttpClient()) {
            client.BaseAddress = new Uri("https://localhost:7291/api/");
            var response = client.PutAsync("Billpay", content).Result;
        }

        return RedirectToAction("Index", new {id = accountnumber});
    }

    public async Task<IActionResult> Unfreeze(string id, int accountnumber) {
        BillPay billPay = await BillPayFetcher.GetBillByIDAsync(id);

        billPay.Status = Status.Awaiting;

        var content = new StringContent(JsonConvert.SerializeObject(billPay), Encoding.UTF8, "application/json");

        using (var client = new HttpClient()) {
            client.BaseAddress = new Uri("https://localhost:7291/api/");
            var response = client.PutAsync("Billpay", content).Result;
        }

        return RedirectToAction("Index", new {id = accountnumber});
    }

}

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Controllers/DetailsController.cs
using AdminWebPortal.Helpers;
using AdminWebPortal.Models;
using AdminWebPortal.Filters;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Net.Http.Headers;

namespace AdminWebPortal.Controllers;

[AuthorizeAdmin]
public class DetailsController : Controller {
    public async Task<IActionResult> Index() {
        string customerID = HttpContext.Session.GetString("customerID");
        //GET:Customers
        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        return View(customer);
    }

    [HttpPost]
    public async Task<IActionResult> Index(string name, string tfn, string address, string suburb, string state, string postcode, string mobile) {
        string customerID = HttpContext.Session.GetString("customerID");
        //GET:Customers
        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        return View(customer);
    }

    
    public async Task<IActionResult> Lock() {
        string customerID = HttpContext.Session.GetString("customerID");

        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        customer.Locked = true;

        var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");

        using (var client = new HttpClient()) {
            client.BaseAddress = new Uri("https://localhost:7291/api/");
            var response = client.PutAsync("Customers", content).Result;
        }

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Unlock() {
        string customerID = HttpContext.Session.GetString("customerID");

        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        customer.Locked = false;

        var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");

        using (var client = new HttpClient()) {
            client.BaseAddress = new Uri("https://localhost:7291/api/");
            var response = client.PutAsync("Customers", content).Result;
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> EditDetails(string name, string tfn, string address, string suburb, string state, string postcode, string mobile) {
        string customerID = HttpContext.Session.GetString("customerID");
        Customer customer = await CustomerFetcher.GetCustomerByIDAsync(customerID);

        customer.Name = name;
        customer.TFN = tfn;
        customer.Address = address;
        customer.Suburb = suburb;
        customer.State = state;
        customer.Postcode = postcode;
        customer.Mobile = mobile;

        var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");

        using (var client = new HttpClient()) {
            client.BaseAddress = new Uri("https://localhost:7291/api/");
            var response = client.PutAsync("Customers", content).Result;
        }

        return RedirectToAction("Index");
    }
}

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Views/AdminPanel/Customer.cshtml
@model Customer
@{
    ViewData["Title"] = "Admin Panel - Customer Management";
}

<div class="text-center">
    <h1 class="display-4">Welcome Administrator</h1>
    @Html.DisplayFor(x => Model.Name)
</div>

<p>
    <a asp-controller="Details" asp-action="Index">Customer Details</a>
</p>

<h3>Account management for @Html.DisplayFor(x=> Model.Name)</h3>
<table class ="table">
    <tr>
        <th>@Html.DisplayNameFor(x=> x.Accounts[0].AccountNumber)</th>
        <th>@Html.DisplayNameFor(x=> x.Accounts[0].AccountType)</th>
        <th></th>
    </tr>
    @foreach(var account in Model.Accounts) {
        <tr>
            <td>@Html.DisplayFor(x => account.AccountNumber)</td>
            <td>@Html.DisplayFor(x => account.AccountType)</td>
            <td>
                <a asp-action="Transactions" asp-route-id="@account.AccountNumber">View Transactions</a>
            </td>
            <td>
                <a asp-controller="BillPay" asp-action="Index" asp-route-id="@account.AccountNumber">Account BillPay</a>
            </td>
        </tr>
    }
</table>

<p>
    <a asp-controller="AdminPanel" asp-action="Index">Back to customer select</a>
</p>

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Views/AdminPanel/Index.cshtml
@model List<Customer>
@{
    ViewData["Title"] = "Admin Panel";
}

<div class="text-center">
    <h1 class="display-4">Welcome Administrator</h1>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Search">
                <div class="form-group">
                    <label for="customerID" class="control-label">CustomerID</label>
                    <input id ="customerID" name="customerID" class="form-control" 
                        data-val="true" data-val-required="CustomerID required"/>                    
                </div>
                <div class ="form-group">
                    <input type="submit" value="Search" class="btn-primary btn-primary" />
                </div>
            </form>
        </div>
    </div>

    @foreach (var customer in Model) {
       @Html.DisplayFor(x => customer.Name);
    }
</div>

Web Development Technologies A2 2022/Admin/AdminWebPortal/AdminWebPortal/Views/AdminPanel/Transactions.cshtml
@model List<Transaction>

@{
    ViewData["Title"] = "Transactions";
}

<h1>Transactions</h1>

<div>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(x => x[0].AccountNumber)</th>
            <th>@Html.DisplayNameFor(x => x[0].DestinationAccountNumber)</th>
            <th>@Html.DisplayNameFor(x => x[0].TransactionType)</th>
            <th>@Html.DisplayNameFor(x => x[0].Amount)</th>
            <th>@Html.DisplayNameFor(x => x[0].Comment)</th>
            <th>@Html.DisplayNameFor(x => x[0].TransactionTimeUTC)</th>
        </tr>
        @foreach(var transaction in Model) {
            <tr>
                <td>@Html.DisplayFor(x => transaction.AccountNumber)</td>
                <td>@Html.DisplayFor(x => transaction.DestinationAccountNumber)</td>
                <td>@Html.DisplayFor(x => transaction.TransactionType)</td>
                <td>@Html.DisplayFor(x => transaction.Amount)</td>
                <td>@Html.DisplayFor(x => transaction.Comment)</td>
                <td>@Html.DisplayFor(x => transaction.TransactionTimeUTC)</td>
            </tr>
        }
    </table>
</div>
<div>
    <a asp-action="Customer">Back to List</a>
</div>