Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Controllers/BillPayController.cs
using Microsoft.AspNetCore.Mvc;
using MCBAWebApplication.Data;
using MCBAWebApplication.Models;
using MCBAWebApplication.Filters;
using Microsoft.EntityFrameworkCore;

namespace MCBAWebApplication.Controllers;

[AuthorizeCustomer]
public class BillPayController : Controller {
    private readonly McbaWebContext _context;

    private int CustomerId => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

    public BillPayController(McbaWebContext context) => _context = context;

    //Billpay landing page
    //Eagerly loads the bills
    //Lazily loads the payees and customers for viewbags
    //Viewbags are used to help populate the tables as the billpay model doesnt contain the relevant data
    public async Task<IActionResult> Index(int id) {
        var bills = await _context.BillPays.Where(bp => bp.AccountNumber == id).ToListAsync();
        var payees = await _context.Payees.ToListAsync();
        var customer = await _context.Customers.FindAsync(CustomerId);

        ViewBag.AccountNumber = id;
        ViewBag.Payees = payees;

        return View(bills);
    }

    //Called from the Index view
    //Gets a bill from the db context matchin the one selected for deletion
    //Removes the bill and then returns the index with the accountnumber
    [HttpPost]
    public async Task<IActionResult> Delete(int id) {
        var bill = await _context.BillPays.FindAsync(id);
        int accountNum = bill.AccountNumber;

        _context.BillPays.Remove(bill);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index), new { accountNum });
    }

    //Called from the Index view
    //Gets a bill from the db context matching the one selected for editing
    //Allows the user to edit the amount and period of their bill
    public async Task<IActionResult> Edit(int id) {
        var bill = await _context.BillPays.FindAsync(id);

        return View(bill);
    }


    //The validation for the Edit action called from the Edit View
    //Submits the changes to the db context
    [HttpPost]
    public async Task<IActionResult> Edit(int id, decimal amount, DateTime scheduleTimeUtc, Period period) {
        var bill = await _context.BillPays.FindAsync(id);

        if (amount < 0)
            ModelState.AddModelError(nameof(amount), "Amount must be positive");
        if (decimal.Round(amount, 2) != amount)
            ModelState.AddModelError(nameof(amount), "Amount cannot have more than 2 decimal places");

        if (scheduleTimeUtc <= DateTime.Now.AddHours(1))
            ModelState.AddModelError(nameof(scheduleTimeUtc), "Please select a future time");

        if (!ModelState.IsValid) {
            return View();
        }

        bill.Amount = amount;
        bill.ScheduleTimeUtc = scheduleTimeUtc;
        bill.Period = period;

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }


    //Called from the Index View
    //Creates a new billpay
    //Takes in an ID to determine account number
    //Gets all payees to populate selection list
    public async Task<IActionResult> Create(int id) {
        ViewBag.AccountNumber = id;
        ViewBag.Payees = await _context.Payees.ToListAsync();

        return View();
    }

    //Validation of Create action
    //Submits the new entry to the db context
    [HttpPost]
    public async Task<IActionResult> Create(int id, int payeeID, decimal amount, DateTime scheduleTimeUtc, Period period) {
        var payees = _context.Payees.ToList();
        var customer = await _context.Customers.FindAsync(CustomerId);

        var accounts = from a in customer.Accounts select a;

        ViewBag.AccountNumber = id;
        ViewBag.Payees = payees;
        ViewBag.Accounts = accounts;


        if (amount < 0)
            ModelState.AddModelError(nameof(amount), "Amount must be positive");
        if (decimal.Round(amount, 2) != amount)
            ModelState.AddModelError(nameof(amount), "Amount cannot have more than 2 decimal places");

        if (scheduleTimeUtc <= DateTime.Now.AddHours(1))
            ModelState.AddModelError(nameof(scheduleTimeUtc), "Please select a future time");

        if (!ModelState.IsValid) {
            return View();
        }

        _context.BillPays.Add(
            new BillPay {
                AccountNumber = id,
                PayeeID = payeeID,
                Amount = amount,
                ScheduleTimeUtc = scheduleTimeUtc,
                Period = period,
                Status = Status.Awaiting
            });

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index), new {id});
    }
}

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MCBAWebApplication.Data;
using MCBAWebApplication.Models;
using MCBAWebApplication.Filters;
using X.PagedList;
using SimpleHashing;

namespace MCBAWebApplication.Controllers;

[AuthorizeCustomer]
public class CustomerController : Controller {
    private readonly McbaWebContext _context;

    //ReSharper disable once PossibleInvalidOperationException
    private int CustomerId => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

    public CustomerController(McbaWebContext context) => _context = context;
    
    //Customer landing page
    //Lazily loads the customer
    public async Task<IActionResult> Index() {
        var customer = await _context.Customers.FindAsync(CustomerId);

        return View(customer);
    }

    //Called from Index page
    //Lazily loads all customer info
    //Allows user to edit profile information
    public async Task<IActionResult> MyProfile() => View(await _context.Customers.FindAsync(CustomerId));

    //Called from MyProfile view
    //Lazily load's the customers info
    //Assigns any changed values to the customer
    //Validates
    //Updates database
    [HttpPost]
    public async Task<IActionResult> MyProfile(string name, string tfn, string address, string suburb, string state, string postcode, string mobile) {
        var customer = await _context.Customers.FindAsync(CustomerId);

        if (name != customer.Name && name != null)
            customer.Name = name;

        if (tfn != customer.TFN && tfn != null)
            customer.TFN = tfn;

        if (address != customer.Address && address != null)
            customer.Address = address;

        if (suburb != customer.Suburb && suburb != null)
            customer.Suburb = suburb;

        if (state != customer.State && state != null)
            customer.State = state;

        if (postcode != customer.Postcode && postcode != null)
            customer.Postcode = postcode;

        if (mobile != customer.Mobile && mobile != null)
            customer.Mobile = mobile;

        await _context.SaveChangesAsync();

        return View(customer);
    }

    //Called from the MyProfile view
    //Changes the users password
    //Submits it to the database hashed
    [HttpPost]
    public async Task<IActionResult> ChangePassword(string password) {
        if(password.Length > 16)
            ModelState.AddModelError(nameof(password), "Password must be less than 16 characters");
        if (!ModelState.IsValid) {
            return RedirectToAction(nameof(MyProfile));
        }

        string hashedPassword = PBKDF2.Hash(password);

        Console.WriteLine(CustomerId.ToString());

        var login = await _context.Logins.Where(x => x.CustomerID == CustomerId).SingleOrDefaultAsync();

        login.PasswordHash = hashedPassword;
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(MyProfile));
    }

    //Called from Index view
    //Lazily loads all of the transactions for the account
    public async Task<IActionResult> MyStatements(int id, int? page) {
        var account = await _context.Accounts.FindAsync(id);

        ViewBag.Balance = account.Balance;

        //Get transactions and sort by date
        var transactions = from t in account.Transactions select t;
        transactions = transactions.OrderByDescending(t => t.TransactionTimeUTC);

        if(page == null)
            page = 1;
        int pageSize = 4;
        int pageNumber = (page ?? 1);

        return View(transactions.ToPagedList(pageNumber, pageSize));
    }
}

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Controllers/DepositController.cs
using Microsoft.AspNetCore.Mvc;
using MCBAWebApplication.Data;
using MCBAWebApplication.Models;
using MCBAWebApplication.Filters;

namespace MCBAWebApplication.Controllers;

[AuthorizeCustomer]
public class DepositController : Controller {
    private readonly McbaWebContext _context;

    private int CustomerId => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

    public DepositController(McbaWebContext context) => _context = context;

    //Called from the Customer index
    //Is given an account number as an id 
    public async Task<IActionResult> Index(int id) => View(await _context.Accounts.FindAsync(id));

    //Called from the Index view
    //Validates the deposit
    [HttpPost]
    public async Task<IActionResult> Index(int id, decimal amount, string comment) {
        var account = await _context.Accounts.FindAsync(id);

        if (amount <= 0)
            ModelState.AddModelError(nameof(amount), "Amount must be positive");
        if (decimal.Round(amount, 2) != amount)
            ModelState.AddModelError(nameof(amount), "Amount mcannot have more than 2 decimal places");
        if (!ModelState.IsValid) { 
            ViewBag.Amount = amount;
            return View(account);
        }

        return RedirectToAction(nameof(Confirmation), new {id, amount, comment});
    }

    //Called from the Index action
    //Asks the user to confirm their deposit
    public async Task<IActionResult> Confirmation(int id, decimal amount, string comment) {
        var account = await _context.Accounts.FindAsync(id);

        ViewBag.amount = amount;
        ViewBag.Comment = comment;
        return View(account);
    }

    //Called from Confirmation view
    //Updates the database with the deposit then returns to Customer index
    [HttpPost]
    public async Task<IActionResult> Deposit(int id, decimal amount, string comment) {
        var account = await _context.Accounts.FindAsync(id);

        account.Balance += amount;
        account.Transactions.Add(
            new Transaction {
                TransactionType = TransactionType.Deposit,
                Amount = amount,
                Comment = comment,
                TransactionTimeUTC = DateTime.UtcNow,
            });

        await _context.SaveChangesAsync();

        return RedirectToAction("Index", "Customer");
    }
}

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Controllers/TransferController.cs
using Microsoft.AspNetCore.Mvc;
using MCBAWebApplication.Data;
using MCBAWebApplication.Models;
using MCBAWebApplication.Filters;

namespace MCBAWebApplication.Controllers;

[AuthorizeCustomer]
public class TransferController : Controller {
    public const decimal SURCHARGE_TRANSFER = 0.10M;
    public const decimal CHECKING_MINIMUM = 300.0M;

    private readonly McbaWebContext _context;

    private int CustomerId => HttpContext.Session.GetInt32(nameof(CustomerId)).Value;

    public TransferController(McbaWebContext context) => _context = context;

    //Called from the Customer index
    //Is given an account number as an id 
    public async Task<IActionResult> Index(int id) => View(await _context.Accounts.FindAsync(id));

    //Called from the Index view
    //Validates the transfer
    [HttpPost]
    public async Task<IActionResult> Index(int id, int destAccountNumber, decimal amount, string comments) {
        var account = await _context.Accounts.FindAsync(id);
        var destinationAccount = await _context.Accounts.FindAsync(destAccountNumber);

        //Using a null reference exception block because FindAsync does not simply return null on a failed search
        try {
            if (destinationAccount.AccountNumber == account.AccountNumber)
                ModelState.AddModelError(nameof(destinationAccount), "Cannot transfer to the same account");
        }
        catch (NullReferenceException) {
            ModelState.AddModelError(nameof(destinationAccount), "The account was not found");
        }

        if (amount <= 0)
            ModelState.AddModelError(nameof(amount), "Amount must be positive");
        if (decimal.Round(amount, 2) != amount)
            ModelState.AddModelError(nameof(amount), "Amount cannot have more than 2 decimal places");
        if (!ModelState.IsValid) {
            ViewBag.ammount = amount;
            return View(account);
        }

        //- - Fees logic - -
        //Check if the user has used their 2 free transactions
        //If so apply a $0.05 surcharge
        //Moved after client only checks because we access the database here

        int transactions = 0;
        foreach (var transaction in account.Transactions) {
            if (transaction.TransactionType == TransactionType.Withdraw || transaction.TransactionType == TransactionType.TransferDebit)
                transactions++;
        }

        if (transactions >= 2) {
            if (account.AccountType == AccountType.Checking) {
                if (account.AccountType == AccountType.Checking && amount > (account.Balance - SURCHARGE_TRANSFER - CHECKING_MINIMUM))
                    ModelState.AddModelError(nameof(amount), "Not enough money to transfer this amount - Checking Accounts need minimum $300 remaining");
            }
            else {
                if (amount > (account.Balance + SURCHARGE_TRANSFER))
                    ModelState.AddModelError(nameof(amount), "Not enough money to transfer this amount");
            }
        }
        else {
            if (account.AccountType == AccountType.Checking) {
                if (account.AccountType == AccountType.Checking && amount > (account.Balance - CHECKING_MINIMUM))
                    ModelState.AddModelError(nameof(amount), "Not enough money to transfer this amount - Checking Accounts need minimum $300 remaining");
            }
            else {
                if (amount > (account.Balance + SURCHARGE_TRANSFER))
                    ModelState.AddModelError(nameof(amount), "Not enough money to transfer this amount");
            }
        }

        if (!ModelState.IsValid) {
            ViewBag.Amount = amount;
            return View(account);
        }

        return RedirectToAction(nameof(Confirmation), new { id, destAccountNumber, amount, comments, transactions });
    }

    //Called from the Index action
    //Asks the user to confirm their transfer
    public async Task<IActionResult> Confirmation(int id, int destAccountNumber, decimal amount, string comments, int transactions) {
        var account = await _context.Accounts.FindAsync(id);
        var destinationAccount = await _context.Accounts.FindAsync(destAccountNumber);

        ViewBag.Amount = amount;
        ViewBag.Comments = comments;
        ViewBag.Transactions = transactions;
        ViewBag.DestAccountNumber = destinationAccount.AccountNumber;

        return View(account);
    }

    //Called from Confirmation view
    //Updates the database with the transfer then returns to Customer index
    [HttpPost]
    public async Task<IActionResult> Transfer(int id, int destAccountNumber, decimal amount, string comments, int transactions) {
        var account = await _context.Accounts.FindAsync(id);
        var destinationAccount = await _context.Accounts.FindAsync(destAccountNumber);

        account.Balance -= amount;
        account.Transactions.Add(
            new Transaction {
                TransactionType = TransactionType.TransferDebit,
                DestinationAccountNumber = destinationAccount.AccountNumber,
                Amount = amount,
                Comment = comments,
                TransactionTimeUTC = DateTime.UtcNow
            });

        await _context.SaveChangesAsync();

        destinationAccount.Balance += amount;
        destinationAccount.Transactions.Add(
            new Transaction {
                TransactionType = TransactionType.TransferCredit,
                Amount = amount,
                Comment = comments,
                TransactionTimeUTC = DateTime.UtcNow
            });

        await _context.SaveChangesAsync();

        if (transactions >= 2) {
            account.Balance -= SURCHARGE_TRANSFER;
            account.Transactions.Add(
                new Transaction {
                    TransactionType = TransactionType.ServiceCharge,
                    Amount = SURCHARGE_TRANSFER,
                    Comment = "Service Fees - Transfer",
                    TransactionTimeUTC = DateTime.UtcNow
                });
        }

        await _context.SaveChangesAsync();

        return RedirectToAction("Index", "Customer");
    }
}

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Views/Customer/ChangePassword.cshtml
@model Login
@{
}
        <form asp-action="ChangePassword">
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label for="Password" class="control-label"></label>
                <input id="Password" name="Password" class="form-control"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Change Password" class="btn btn-primary" />
            </div>
        </form>

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Views/Customer/Index.cshtml
@model Customer
@{
    ViewData["Title"] = "Accounts";
}

<div>
    <h1 class="display-4">Welcome, @Model.Name</h1>
    
    <h3>Your Accounts</h3>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(x => x.Accounts[0].AccountNumber)</th>
            <th>@Html.DisplayNameFor(x => x.Accounts[0].AccountType)</th>
            <th>@Html.DisplayNameFor(x => x.Accounts[0].Balance)</th>
            <th></th>
        </tr>
        @foreach(var account in Model.Accounts) {
            <tr>
                <td>@Html.DisplayFor(x => account.AccountNumber)</td>
                <td>@Html.DisplayFor(x => account.AccountType)</td>
                <td>@Html.DisplayFor(x => account.Balance)</td>
                <td>
                    <a class="btn btn-primary"
                        asp-controller="Deposit" asp-action="Index" asp-route-id="@account.AccountNumber">Deposit</a>

                    <a class="btn btn-primary"
                        asp-controller="Withdraw" asp-action="Index" asp-route-id="@account.AccountNumber">Withdraw</a>

                    <a class="btn btn-primary"
                        asp-controller="Transfer" asp-action="Index" asp-route-id="@account.AccountNumber">Transfer</a>

                    <a class="btn btn-primary"
                        asp-action="MyStatements" asp-route-id="@account.AccountNumber">MyStatements</a>

                    <a class="btn btn-primary"
                        asp-controller="BillPay" asp-action="Index" asp-route-id="@account.AccountNumber">BillPay</a>
                </td>
            </tr>
        }
    </table>
    <a class="btn btn-primary"
        asp-action="MyProfile">MyProfile</a>
</div>

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Views/Customer/MyProfile.cshtml
@model MCBAWebApplication.Models.Customer

@{
    ViewData["Title"] = "MyProfile";
    Login login = new Login();
}

<h1>MyProfile</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MyProfile">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TFN" class="control-label"></label>
                <input asp-for="TFN" class="form-control" />
                <span asp-validation-for="TFN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Suburb" class="control-label"></label>
                <input asp-for="Suburb" class="form-control" />
                <span asp-validation-for="Suburb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postcode" class="control-label"></label>
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div>
        <form asp-action="ChangePassword">
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label for="Password" class="control-label"></label>
                <input id="Password" name="Password" class="form-control"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Change Password" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web Development Technologies A2 2022/MCBAWebApplication/MCBAWebApplication/Views/Customer/MyStatements.cshtml
@model X.PagedList.IPagedList<MCBAWebApplication.Models.Transaction>
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "MyStatements";
}

<div>
    Balance: @ViewBag.Balance?.ToString("0.00")

    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(x => x[0].Amount)</th>
            <th>@Html.DisplayNameFor(x => x[0].DestinationAccount)</th>
            <th>@Html.DisplayNameFor(x => x[0].TransactionType)</th>
            <th>@Html.DisplayNameFor(x => x[0].Comment)</th>
            <th>Transaction Time</th>
            <th></th>
        </tr>

    @foreach (var transaction in Model){
        DateTime dateTime = transaction.TransactionTimeUTC.ToLocalTime();
        <tr>
            <td>@Html.DisplayFor(x => transaction.Amount)</td>
            <td>@Html.DisplayFor(x => transaction.DestinationAccountNumber)</td>
            <td>@Html.DisplayFor(x => transaction.TransactionType)</td>
            <td>@Html.DisplayFor(x => transaction.Comment)</td>
            <td>@Html.DisplayFor(x => dateTime)</td>
        </tr>
    }
    </table>
</div>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("MyStatements", new{page}))

<div>
    <a asp-controller="Customer" asp-action="Index">Back to List</a>
</div>